import React from 'react';
export const audio_engineDetails = () => <div>audio_engine details for Audio engine - playback, tempo, time-stretch, pitch shift</div>;
export const audio_engine_detail_0 = (p:any)=> <div>audio_engine 0 120bpm</div>;
export const audio_engine_detail_1 = (p:any)=> <div>audio_engine 1 44.1k</div>;
export const audio_engine_detail_2 = (p:any)=> <div>audio_engine 2 stretch</div>;
export const audio_engine_detail_3 = (p:any)=> <div>audio_engine 3 pitch</div>;
export const audio_engine_detail_4 = (p:any)=> <div>audio_engine 4 120bpm</div>;
export const audio_engine_detail_5 = (p:any)=> <div>audio_engine 5 44.1k</div>;
export const audio_engine_detail_6 = (p:any)=> <div>audio_engine 6 stretch</div>;
export const audio_engine_detail_7 = (p:any)=> <div>audio_engine 7 pitch</div>;
export const audio_engine_detail_8 = (p:any)=> <div>audio_engine 8 120bpm</div>;
export const audio_engine_detail_9 = (p:any)=> <div>audio_engine 9 44.1k</div>;
export const audio_engine_detail_10 = (p:any)=> <div>audio_engine 10 stretch</div>;
export const audio_engine_detail_11 = (p:any)=> <div>audio_engine 11 pitch</div>;
export const audio_engine_detail_12 = (p:any)=> <div>audio_engine 12 120bpm</div>;
export const audio_engine_detail_13 = (p:any)=> <div>audio_engine 13 44.1k</div>;
export const audio_engine_detail_14 = (p:any)=> <div>audio_engine 14 stretch</div>;
export const audio_engine_detail_15 = (p:any)=> <div>audio_engine 15 pitch</div>;
export const audio_engine_detail_16 = (p:any)=> <div>audio_engine 16 120bpm</div>;
export const audio_engine_detail_17 = (p:any)=> <div>audio_engine 17 44.1k</div>;
export const audio_engine_detail_18 = (p:any)=> <div>audio_engine 18 stretch</div>;
export const audio_engine_detail_19 = (p:any)=> <div>audio_engine 19 pitch</div>;