import React from 'react';
export const effectsDetails = () => <div>effects details for Effects - reverb, delay, chorus, distortion</div>;
export const effects_detail_0 = (p:any)=> <div>effects 0 reverb</div>;
export const effects_detail_1 = (p:any)=> <div>effects 1 delay</div>;
export const effects_detail_2 = (p:any)=> <div>effects 2 chorus</div>;
export const effects_detail_3 = (p:any)=> <div>effects 3 distortion</div>;
export const effects_detail_4 = (p:any)=> <div>effects 4 reverb</div>;
export const effects_detail_5 = (p:any)=> <div>effects 5 delay</div>;
export const effects_detail_6 = (p:any)=> <div>effects 6 chorus</div>;
export const effects_detail_7 = (p:any)=> <div>effects 7 distortion</div>;
export const effects_detail_8 = (p:any)=> <div>effects 8 reverb</div>;
export const effects_detail_9 = (p:any)=> <div>effects 9 delay</div>;
export const effects_detail_10 = (p:any)=> <div>effects 10 chorus</div>;
export const effects_detail_11 = (p:any)=> <div>effects 11 distortion</div>;
export const effects_detail_12 = (p:any)=> <div>effects 12 reverb</div>;
export const effects_detail_13 = (p:any)=> <div>effects 13 delay</div>;
export const effects_detail_14 = (p:any)=> <div>effects 14 chorus</div>;
export const effects_detail_15 = (p:any)=> <div>effects 15 distortion</div>;
export const effects_detail_16 = (p:any)=> <div>effects 16 reverb</div>;
export const effects_detail_17 = (p:any)=> <div>effects 17 delay</div>;
export const effects_detail_18 = (p:any)=> <div>effects 18 chorus</div>;
export const effects_detail_19 = (p:any)=> <div>effects 19 distortion</div>;