import React from 'react';
export const analyticsDetails = () => <div>analytics details for Analytics - play count, skip, complexity score</div>;
export const analytics_detail_0 = (p:any)=> <div>analytics 0 plays</div>;
export const analytics_detail_1 = (p:any)=> <div>analytics 1 skips</div>;
export const analytics_detail_2 = (p:any)=> <div>analytics 2 complexity</div>;
export const analytics_detail_3 = (p:any)=> <div>analytics 3 plays</div>;
export const analytics_detail_4 = (p:any)=> <div>analytics 4 skips</div>;
export const analytics_detail_5 = (p:any)=> <div>analytics 5 complexity</div>;
export const analytics_detail_6 = (p:any)=> <div>analytics 6 plays</div>;
export const analytics_detail_7 = (p:any)=> <div>analytics 7 skips</div>;
export const analytics_detail_8 = (p:any)=> <div>analytics 8 complexity</div>;
export const analytics_detail_9 = (p:any)=> <div>analytics 9 plays</div>;
export const analytics_detail_10 = (p:any)=> <div>analytics 10 skips</div>;
export const analytics_detail_11 = (p:any)=> <div>analytics 11 complexity</div>;
export const analytics_detail_12 = (p:any)=> <div>analytics 12 plays</div>;
export const analytics_detail_13 = (p:any)=> <div>analytics 13 skips</div>;
export const analytics_detail_14 = (p:any)=> <div>analytics 14 complexity</div>;
export const analytics_detail_15 = (p:any)=> <div>analytics 15 plays</div>;
export const analytics_detail_16 = (p:any)=> <div>analytics 16 skips</div>;
export const analytics_detail_17 = (p:any)=> <div>analytics 17 complexity</div>;
export const analytics_detail_18 = (p:any)=> <div>analytics 18 plays</div>;
export const analytics_detail_19 = (p:any)=> <div>analytics 19 skips</div>;