import React from 'react';
export const tempoDetails = () => <div>tempo details for Tempo map - BPM, time sig, automation</div>;
export const tempo_detail_0 = (p:any)=> <div>tempo 0 4/4</div>;
export const tempo_detail_1 = (p:any)=> <div>tempo 1 3/4</div>;
export const tempo_detail_2 = (p:any)=> <div>tempo 2 120</div>;
export const tempo_detail_3 = (p:any)=> <div>tempo 3 automation</div>;
export const tempo_detail_4 = (p:any)=> <div>tempo 4 4/4</div>;
export const tempo_detail_5 = (p:any)=> <div>tempo 5 3/4</div>;
export const tempo_detail_6 = (p:any)=> <div>tempo 6 120</div>;
export const tempo_detail_7 = (p:any)=> <div>tempo 7 automation</div>;
export const tempo_detail_8 = (p:any)=> <div>tempo 8 4/4</div>;
export const tempo_detail_9 = (p:any)=> <div>tempo 9 3/4</div>;
export const tempo_detail_10 = (p:any)=> <div>tempo 10 120</div>;
export const tempo_detail_11 = (p:any)=> <div>tempo 11 automation</div>;
export const tempo_detail_12 = (p:any)=> <div>tempo 12 4/4</div>;
export const tempo_detail_13 = (p:any)=> <div>tempo 13 3/4</div>;
export const tempo_detail_14 = (p:any)=> <div>tempo 14 120</div>;
export const tempo_detail_15 = (p:any)=> <div>tempo 15 automation</div>;
export const tempo_detail_16 = (p:any)=> <div>tempo 16 4/4</div>;
export const tempo_detail_17 = (p:any)=> <div>tempo 17 3/4</div>;
export const tempo_detail_18 = (p:any)=> <div>tempo 18 120</div>;
export const tempo_detail_19 = (p:any)=> <div>tempo 19 automation</div>;