import React from 'react';
export const mixingDetails = () => <div>mixing details for Stem mixing - gain, pan, EQ, compression, reverb per stem</div>;
export const mixing_detail_0 = (p:any)=> <div>mixing 0 vocals</div>;
export const mixing_detail_1 = (p:any)=> <div>mixing 1 drums</div>;
export const mixing_detail_2 = (p:any)=> <div>mixing 2 bass</div>;
export const mixing_detail_3 = (p:any)=> <div>mixing 3 guitar</div>;
export const mixing_detail_4 = (p:any)=> <div>mixing 4 keys</div>;
export const mixing_detail_5 = (p:any)=> <div>mixing 5 vocals</div>;
export const mixing_detail_6 = (p:any)=> <div>mixing 6 drums</div>;
export const mixing_detail_7 = (p:any)=> <div>mixing 7 bass</div>;
export const mixing_detail_8 = (p:any)=> <div>mixing 8 guitar</div>;
export const mixing_detail_9 = (p:any)=> <div>mixing 9 keys</div>;
export const mixing_detail_10 = (p:any)=> <div>mixing 10 vocals</div>;
export const mixing_detail_11 = (p:any)=> <div>mixing 11 drums</div>;
export const mixing_detail_12 = (p:any)=> <div>mixing 12 bass</div>;
export const mixing_detail_13 = (p:any)=> <div>mixing 13 guitar</div>;
export const mixing_detail_14 = (p:any)=> <div>mixing 14 keys</div>;
export const mixing_detail_15 = (p:any)=> <div>mixing 15 vocals</div>;
export const mixing_detail_16 = (p:any)=> <div>mixing 16 drums</div>;
export const mixing_detail_17 = (p:any)=> <div>mixing 17 bass</div>;
export const mixing_detail_18 = (p:any)=> <div>mixing 18 guitar</div>;
export const mixing_detail_19 = (p:any)=> <div>mixing 19 keys</div>;