import React from 'react';
export const instrumentsDetails = () => <div>instruments details for Instruments - synth, sampler, drum machine</div>;
export const instruments_detail_0 = (p:any)=> <div>instruments 0 synth</div>;
export const instruments_detail_1 = (p:any)=> <div>instruments 1 sampler</div>;
export const instruments_detail_2 = (p:any)=> <div>instruments 2 drums</div>;
export const instruments_detail_3 = (p:any)=> <div>instruments 3 synth</div>;
export const instruments_detail_4 = (p:any)=> <div>instruments 4 sampler</div>;
export const instruments_detail_5 = (p:any)=> <div>instruments 5 drums</div>;
export const instruments_detail_6 = (p:any)=> <div>instruments 6 synth</div>;
export const instruments_detail_7 = (p:any)=> <div>instruments 7 sampler</div>;
export const instruments_detail_8 = (p:any)=> <div>instruments 8 drums</div>;
export const instruments_detail_9 = (p:any)=> <div>instruments 9 synth</div>;
export const instruments_detail_10 = (p:any)=> <div>instruments 10 sampler</div>;
export const instruments_detail_11 = (p:any)=> <div>instruments 11 drums</div>;
export const instruments_detail_12 = (p:any)=> <div>instruments 12 synth</div>;
export const instruments_detail_13 = (p:any)=> <div>instruments 13 sampler</div>;
export const instruments_detail_14 = (p:any)=> <div>instruments 14 drums</div>;
export const instruments_detail_15 = (p:any)=> <div>instruments 15 synth</div>;
export const instruments_detail_16 = (p:any)=> <div>instruments 16 sampler</div>;
export const instruments_detail_17 = (p:any)=> <div>instruments 17 drums</div>;
export const instruments_detail_18 = (p:any)=> <div>instruments 18 synth</div>;
export const instruments_detail_19 = (p:any)=> <div>instruments 19 sampler</div>;