import React from 'react';
export const catalogDetails = () => <div>catalog details for Sample catalog - metadata, search, tagging</div>;
export const catalog_detail_0 = (p:any)=> <div>catalog 0 genre</div>;
export const catalog_detail_1 = (p:any)=> <div>catalog 1 bpm</div>;
export const catalog_detail_2 = (p:any)=> <div>catalog 2 key</div>;
export const catalog_detail_3 = (p:any)=> <div>catalog 3 instrument</div>;
export const catalog_detail_4 = (p:any)=> <div>catalog 4 genre</div>;
export const catalog_detail_5 = (p:any)=> <div>catalog 5 bpm</div>;
export const catalog_detail_6 = (p:any)=> <div>catalog 6 key</div>;
export const catalog_detail_7 = (p:any)=> <div>catalog 7 instrument</div>;
export const catalog_detail_8 = (p:any)=> <div>catalog 8 genre</div>;
export const catalog_detail_9 = (p:any)=> <div>catalog 9 bpm</div>;
export const catalog_detail_10 = (p:any)=> <div>catalog 10 key</div>;
export const catalog_detail_11 = (p:any)=> <div>catalog 11 instrument</div>;
export const catalog_detail_12 = (p:any)=> <div>catalog 12 genre</div>;
export const catalog_detail_13 = (p:any)=> <div>catalog 13 bpm</div>;
export const catalog_detail_14 = (p:any)=> <div>catalog 14 key</div>;
export const catalog_detail_15 = (p:any)=> <div>catalog 15 instrument</div>;
export const catalog_detail_16 = (p:any)=> <div>catalog 16 genre</div>;
export const catalog_detail_17 = (p:any)=> <div>catalog 17 bpm</div>;
export const catalog_detail_18 = (p:any)=> <div>catalog 18 key</div>;
export const catalog_detail_19 = (p:any)=> <div>catalog 19 instrument</div>;