import React from 'react';
export const collabDetails = () => <div>collab details for Collaboration - share, version, comments, merge</div>;
export const collab_detail_0 = (p:any)=> <div>collab 0 share</div>;
export const collab_detail_1 = (p:any)=> <div>collab 1 version</div>;
export const collab_detail_2 = (p:any)=> <div>collab 2 comment</div>;
export const collab_detail_3 = (p:any)=> <div>collab 3 merge</div>;
export const collab_detail_4 = (p:any)=> <div>collab 4 share</div>;
export const collab_detail_5 = (p:any)=> <div>collab 5 version</div>;
export const collab_detail_6 = (p:any)=> <div>collab 6 comment</div>;
export const collab_detail_7 = (p:any)=> <div>collab 7 merge</div>;
export const collab_detail_8 = (p:any)=> <div>collab 8 share</div>;
export const collab_detail_9 = (p:any)=> <div>collab 9 version</div>;
export const collab_detail_10 = (p:any)=> <div>collab 10 comment</div>;
export const collab_detail_11 = (p:any)=> <div>collab 11 merge</div>;
export const collab_detail_12 = (p:any)=> <div>collab 12 share</div>;
export const collab_detail_13 = (p:any)=> <div>collab 13 version</div>;
export const collab_detail_14 = (p:any)=> <div>collab 14 comment</div>;
export const collab_detail_15 = (p:any)=> <div>collab 15 merge</div>;
export const collab_detail_16 = (p:any)=> <div>collab 16 share</div>;
export const collab_detail_17 = (p:any)=> <div>collab 17 version</div>;
export const collab_detail_18 = (p:any)=> <div>collab 18 comment</div>;
export const collab_detail_19 = (p:any)=> <div>collab 19 merge</div>;