import React from 'react';
export const harmonyDetails = () => <div>harmony details for Harmony engine - chords, roman numerals, cadence, modal interchange</div>;
export const harmony_detail_0 = (p:any)=> <div>harmony 0 C</div>;
export const harmony_detail_1 = (p:any)=> <div>harmony 1 G</div>;
export const harmony_detail_2 = (p:any)=> <div>harmony 2 Am</div>;
export const harmony_detail_3 = (p:any)=> <div>harmony 3 F</div>;
export const harmony_detail_4 = (p:any)=> <div>harmony 4 Dm</div>;
export const harmony_detail_5 = (p:any)=> <div>harmony 5 Em</div>;
export const harmony_detail_6 = (p:any)=> <div>harmony 6 C</div>;
export const harmony_detail_7 = (p:any)=> <div>harmony 7 G</div>;
export const harmony_detail_8 = (p:any)=> <div>harmony 8 Am</div>;
export const harmony_detail_9 = (p:any)=> <div>harmony 9 F</div>;
export const harmony_detail_10 = (p:any)=> <div>harmony 10 Dm</div>;
export const harmony_detail_11 = (p:any)=> <div>harmony 11 Em</div>;
export const harmony_detail_12 = (p:any)=> <div>harmony 12 C</div>;
export const harmony_detail_13 = (p:any)=> <div>harmony 13 G</div>;
export const harmony_detail_14 = (p:any)=> <div>harmony 14 Am</div>;
export const harmony_detail_15 = (p:any)=> <div>harmony 15 F</div>;
export const harmony_detail_16 = (p:any)=> <div>harmony 16 Dm</div>;
export const harmony_detail_17 = (p:any)=> <div>harmony 17 Em</div>;
export const harmony_detail_18 = (p:any)=> <div>harmony 18 C</div>;
export const harmony_detail_19 = (p:any)=> <div>harmony 19 G</div>;