import React from 'react';
export const stemsDetails = () => <div>stems details for Stem separation - vocal/instrument isolation, gain staging</div>;
export const stems_detail_0 = (p:any)=> <div>stems 0 vocal</div>;
export const stems_detail_1 = (p:any)=> <div>stems 1 drum</div>;
export const stems_detail_2 = (p:any)=> <div>stems 2 bass</div>;
export const stems_detail_3 = (p:any)=> <div>stems 3 other</div>;
export const stems_detail_4 = (p:any)=> <div>stems 4 vocal</div>;
export const stems_detail_5 = (p:any)=> <div>stems 5 drum</div>;
export const stems_detail_6 = (p:any)=> <div>stems 6 bass</div>;
export const stems_detail_7 = (p:any)=> <div>stems 7 other</div>;
export const stems_detail_8 = (p:any)=> <div>stems 8 vocal</div>;
export const stems_detail_9 = (p:any)=> <div>stems 9 drum</div>;
export const stems_detail_10 = (p:any)=> <div>stems 10 bass</div>;
export const stems_detail_11 = (p:any)=> <div>stems 11 other</div>;
export const stems_detail_12 = (p:any)=> <div>stems 12 vocal</div>;
export const stems_detail_13 = (p:any)=> <div>stems 13 drum</div>;
export const stems_detail_14 = (p:any)=> <div>stems 14 bass</div>;
export const stems_detail_15 = (p:any)=> <div>stems 15 other</div>;
export const stems_detail_16 = (p:any)=> <div>stems 16 vocal</div>;
export const stems_detail_17 = (p:any)=> <div>stems 17 drum</div>;
export const stems_detail_18 = (p:any)=> <div>stems 18 bass</div>;
export const stems_detail_19 = (p:any)=> <div>stems 19 other</div>;