import React from 'react';
export const exportDetails = () => <div>export details for Export - stems, stems + master, metadata DB</div>;
export const export_detail_0 = (p:any)=> <div>export 0 wav</div>;
export const export_detail_1 = (p:any)=> <div>export 1 mp3</div>;
export const export_detail_2 = (p:any)=> <div>export 2 toml</div>;
export const export_detail_3 = (p:any)=> <div>export 3 db</div>;
export const export_detail_4 = (p:any)=> <div>export 4 wav</div>;
export const export_detail_5 = (p:any)=> <div>export 5 mp3</div>;
export const export_detail_6 = (p:any)=> <div>export 6 toml</div>;
export const export_detail_7 = (p:any)=> <div>export 7 db</div>;
export const export_detail_8 = (p:any)=> <div>export 8 wav</div>;
export const export_detail_9 = (p:any)=> <div>export 9 mp3</div>;
export const export_detail_10 = (p:any)=> <div>export 10 toml</div>;
export const export_detail_11 = (p:any)=> <div>export 11 db</div>;
export const export_detail_12 = (p:any)=> <div>export 12 wav</div>;
export const export_detail_13 = (p:any)=> <div>export 13 mp3</div>;
export const export_detail_14 = (p:any)=> <div>export 14 toml</div>;
export const export_detail_15 = (p:any)=> <div>export 15 db</div>;
export const export_detail_16 = (p:any)=> <div>export 16 wav</div>;
export const export_detail_17 = (p:any)=> <div>export 17 mp3</div>;
export const export_detail_18 = (p:any)=> <div>export 18 toml</div>;
export const export_detail_19 = (p:any)=> <div>export 19 db</div>;