import React from 'react';
export const dawDetails = () => <div>daw details for DAW core - tracks, clips, arrangement, timeline</div>;
export const daw_detail_0 = (p:any)=> <div>daw 0 tracks</div>;
export const daw_detail_1 = (p:any)=> <div>daw 1 clips</div>;
export const daw_detail_2 = (p:any)=> <div>daw 2 arrangement</div>;
export const daw_detail_3 = (p:any)=> <div>daw 3 automation</div>;
export const daw_detail_4 = (p:any)=> <div>daw 4 tracks</div>;
export const daw_detail_5 = (p:any)=> <div>daw 5 clips</div>;
export const daw_detail_6 = (p:any)=> <div>daw 6 arrangement</div>;
export const daw_detail_7 = (p:any)=> <div>daw 7 automation</div>;
export const daw_detail_8 = (p:any)=> <div>daw 8 tracks</div>;
export const daw_detail_9 = (p:any)=> <div>daw 9 clips</div>;
export const daw_detail_10 = (p:any)=> <div>daw 10 arrangement</div>;
export const daw_detail_11 = (p:any)=> <div>daw 11 automation</div>;
export const daw_detail_12 = (p:any)=> <div>daw 12 tracks</div>;
export const daw_detail_13 = (p:any)=> <div>daw 13 clips</div>;
export const daw_detail_14 = (p:any)=> <div>daw 14 arrangement</div>;
export const daw_detail_15 = (p:any)=> <div>daw 15 automation</div>;
export const daw_detail_16 = (p:any)=> <div>daw 16 tracks</div>;
export const daw_detail_17 = (p:any)=> <div>daw 17 clips</div>;
export const daw_detail_18 = (p:any)=> <div>daw 18 arrangement</div>;
export const daw_detail_19 = (p:any)=> <div>daw 19 automation</div>;