import React from 'react';
export const masteringDetails = () => <div>mastering details for Mastering - loudness, export, dBFS, LUFS</div>;
export const mastering_detail_0 = (p:any)=> <div>mastering 0 -14 LUFS</div>;
export const mastering_detail_1 = (p:any)=> <div>mastering 1 dBFS</div>;
export const mastering_detail_2 = (p:any)=> <div>mastering 2 export wav</div>;
export const mastering_detail_3 = (p:any)=> <div>mastering 3 -14 LUFS</div>;
export const mastering_detail_4 = (p:any)=> <div>mastering 4 dBFS</div>;
export const mastering_detail_5 = (p:any)=> <div>mastering 5 export wav</div>;
export const mastering_detail_6 = (p:any)=> <div>mastering 6 -14 LUFS</div>;
export const mastering_detail_7 = (p:any)=> <div>mastering 7 dBFS</div>;
export const mastering_detail_8 = (p:any)=> <div>mastering 8 export wav</div>;
export const mastering_detail_9 = (p:any)=> <div>mastering 9 -14 LUFS</div>;
export const mastering_detail_10 = (p:any)=> <div>mastering 10 dBFS</div>;
export const mastering_detail_11 = (p:any)=> <div>mastering 11 export wav</div>;
export const mastering_detail_12 = (p:any)=> <div>mastering 12 -14 LUFS</div>;
export const mastering_detail_13 = (p:any)=> <div>mastering 13 dBFS</div>;
export const mastering_detail_14 = (p:any)=> <div>mastering 14 export wav</div>;
export const mastering_detail_15 = (p:any)=> <div>mastering 15 -14 LUFS</div>;
export const mastering_detail_16 = (p:any)=> <div>mastering 16 dBFS</div>;
export const mastering_detail_17 = (p:any)=> <div>mastering 17 export wav</div>;
export const mastering_detail_18 = (p:any)=> <div>mastering 18 -14 LUFS</div>;
export const mastering_detail_19 = (p:any)=> <div>mastering 19 dBFS</div>;