import React from 'react';
export const notationDetails = () => <div>notation details for Notation - MIDI, sheet, transposition, notemap v2</div>;
export const notation_detail_0 = (p:any)=> <div>notation 0 C4</div>;
export const notation_detail_1 = (p:any)=> <div>notation 1 G3</div>;
export const notation_detail_2 = (p:any)=> <div>notation 2 MIDI</div>;
export const notation_detail_3 = (p:any)=> <div>notation 3 MusicXML</div>;
export const notation_detail_4 = (p:any)=> <div>notation 4 C4</div>;
export const notation_detail_5 = (p:any)=> <div>notation 5 G3</div>;
export const notation_detail_6 = (p:any)=> <div>notation 6 MIDI</div>;
export const notation_detail_7 = (p:any)=> <div>notation 7 MusicXML</div>;
export const notation_detail_8 = (p:any)=> <div>notation 8 C4</div>;
export const notation_detail_9 = (p:any)=> <div>notation 9 G3</div>;
export const notation_detail_10 = (p:any)=> <div>notation 10 MIDI</div>;
export const notation_detail_11 = (p:any)=> <div>notation 11 MusicXML</div>;
export const notation_detail_12 = (p:any)=> <div>notation 12 C4</div>;
export const notation_detail_13 = (p:any)=> <div>notation 13 G3</div>;
export const notation_detail_14 = (p:any)=> <div>notation 14 MIDI</div>;
export const notation_detail_15 = (p:any)=> <div>notation 15 MusicXML</div>;
export const notation_detail_16 = (p:any)=> <div>notation 16 C4</div>;
export const notation_detail_17 = (p:any)=> <div>notation 17 G3</div>;
export const notation_detail_18 = (p:any)=> <div>notation 18 MIDI</div>;
export const notation_detail_19 = (p:any)=> <div>notation 19 MusicXML</div>;